#ifndef SIMPLECC_TRANSFORM_TRIVIALCONSTANTFOLDER_H
#define SIMPLECC_TRANSFORM_TRIVIALCONSTANTFOLDER_H
namespace simplecc {

class TrivialConstantFolder {

};

}
#endif //SIMPLECC_TRANSFORM_TRIVIALCONSTANTFOLDER_H
